a=input("Enter the first number: ")
b=input("Enter the second number: ")
c=int(a)+int(b)
d=int(a)-int(b)
e=int(a)*int(b)
f=float(a)/float(b)
print("Addition:",c)
print("Subtraction:",d)
print("Multiplication:",e)
print("Division:",f)
